[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
async-trait = "0.1.63"
serde = { version = "1.0.152", features = ["derive"] }
sqlx = { version = "0.6.2", features = ["mysql", "runtime-tokio-rustls", "macros", "time", "offline"] }
nanoid = "0.4.0"
time = { version = "0.3.17", features = ["serde"] }
dotenvy = "0.15.6"
tokio = { version = "1.21.2", features = ["full"] }


