[package]
name = "grpc-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1" }
dotenv = "0.15"
async-trait = "0.1"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
tokio = { version = "1.21.2", features = ["full"] }
tonic = "0.8.2"
prost = "0.11.2"

[build-dependencies]
tonic-build = "0.8"
